version: '3'

services:
  holio-go:
    image: holio-go:latest  
    container_name: holio-go2_c
    environment:
      - PORT=${PORT}
      - DB_URI=${DB_URI}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "8080:8080"
